### ISSUE TITLE
Create the Landing page for the Website 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/Hacktoberfest2023#1]
## Tasks :

- Create a Component in the `./src/Component/Home.jsx` 
- Use any Components from the `./src/Components/**/` 
- Use them to create the basic UI of the Landing page.

#### NOTE: You are allowed to create additional components in the `./src/Components/` directory and use them in the `Home.jsx` file.

**Comment by ANKITy102** [comment]
@pooranjoyb please, assign me this issue.

**Comment by pooranjoyb** [comment]
> @pooranjoyb please, assign me this issue.

Go Ahead! Happy Contributing 😄 🚀

**Comment by mohitsaini07** [comment]
Hi @pooranjoyb, Can you assign this issue to me if available?
